http___comment___: HTTP server configuration
http:
  host___comment___: The IP address the server will bind to
  host: ___ip_address___

  port___comment___: The port the server will listen on
  port: 8052
