http______:
http_______: HTTP server configuration
http:
  host______:
  host_______: The IP address the server will bind to
  host: ___ip_address___

  port______:
  port_______: The port the server will listen on
  port: 8052
