http______:
http_______: HTTP server configuration
http:
  host______:
  host_______: The IP address the server will bind to
  host: ___ip_address___

  port______:
  port_______: The port the server will listen on
  port: 8052

log______:
log_______: Logging configuration
log:
  compress______:
  compress_______: Whether to compress old log files
  compress: false

  debug______:
  debug_______: Logging level or mode (e.g., debug, production)
  debug: production

  dir______:
  dir_______: Directory where log files will be stored
  dir: /var/log/___project_name___

  max_age______:
  max_age_______: Maximum number of days to retain old log files
  max_age: 28

  max_backups______:
  max_backups_______: Maximum number of backup log files to keep
  max_backups: 5

  max_size______:
  max_size_______: Maximum size (in MB) of a log file before it gets rotated
  max_size: 20
