http______:
http_______: HTTP server configuration
http:
  host______:
  host_______: The IP address the HTTP server will bind to
  host: ___ip_address___

  port______:
  port_______: The port the HTTP server will listen on
  port: 8052

log______:
log_______: Logging configuration
log:
  compress______:
  compress_______: Whether to compress rotated log files
  compress: false

  debug______:
  debug_______: Logging level (e.g., debug, info, production)
  debug: production

  dir______:
  dir_______: Directory where log files will be stored
  dir: /var/log/___project_name___

  max_age______:
  max_age_______: Number of days to keep old log files
  max_age: 28

  max_backups______:
  max_backups_______: Number of rotated log files to keep
  max_backups: 5

  max_size______:
  max_size_______: Maximum size (in MB) of a log file before it gets rotated
  max_size: 20

auth______:
auth_______: Authentication and token settings
auth:
  access_token_ttl______:
  access_token_ttl_______: Access token time-to-live in minutes
  access_token_ttl: 15

  key______:
  key_______: Secret key for signing tokens
  key: ___random64___

  refresh_token_ttl______:
  refresh_token_ttl_______: Refresh token time-to-live in minutes
  refresh_token_ttl: 540

db______:
db_______: Database connection configuration
db:
  dsn______:
  dsn_______: PostgreSQL DSN connection string
  dsn: postgres:postgres@___ip_address___:5432/postgres?sslmode=disable

  max_idle_conn______:
  max_idle_conn_______: Maximum number of idle database connections
  max_idle_conn: 10

  max_open_conn______:
  max_open_conn_______: Maximum number of open database connections
  max_open_conn: 100

redis______:
redis_______: Redis configuration
redis:
  address______:
  address_______: Redis server address list
  address:
    - localhost:6379

  cluster_mode______:
  cluster_mode_______: Enable Redis cluster mode
  cluster_mode: false

  db______:
  db_______: Redis database index
  db: 1

  max_retry______:
  max_retry_______: Maximum number of retry attempts
  max_retry________: for failed Redis commands
  max_retry: 10

  password______:
  password_______: Redis password (optional)
  password:

  username______:
  username_______: Redis username (optional, for ACL-enabled Redis)
  username:

salt______:
salt_______: Salt used for password hashing
salt:
  password______:
  password_______: Salt value used to hash user passwords
  password: ___random32___
