str___comment___: Str comment
str: str
number___comment___: Number comment
number___comment___1: Number comment1
number___comment___2: Number comment1
number: 1
boolean___comment___: Boolean comment
boolean: true