array:
  -
    map_str: map_str
    map_number: 2
    map_boolean: false
    map_array_str: [ str1, str2, str3 ]
    map_array_number: [ 1, 2, 3 ]
    map_array_boolean: [ true, false, true ]
  -
    map_str: map_str2
    map_number: 2
    map_boolean: false
    map_boolean___comment___: Some comments
    map_array_str: [ str4, str5, str6 ]
    map_array_str___comment___: Some comments
    map_array_number: [ 4, 5, 6 ]
    map_array_boolean: [ false, true, false ]
    map_array_boolean___comment___: Some comments
array2: [ 1, 2, 3 ]
array3: [ str1, str2, str3 ]
array4: [ true, false, true ]